### ISSUE TITLE
the problem to load pretrain model

### ISSUE THREAD

**Issue by stm233** [RenYang-home/RLVC#1] opened 2021-01-18 06:03 UTC
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key MV_analysis/layer_1/signal_conv2d_1/bias not found in checkpoint
         [[{{node save/RestoreV2}}]]

**I guess this problem is caused by the saver and network did not match?**

BTW, whether i could get the training code, not just inference code THX

**Comment by ryangBUAA** [comment] 2021-01-18 19:07
Which tensorflow and tensorflow-compression versions do you use? Since we pre-trained the models on tensorflow 1.12 and tensorflow-compression 1.0 (refer to readme), the codes are currently not compatible with higher versions. 

We are not planning to release the training codes. Sorry for the inconvenience. 

I will currently close this comment, if the problem is not solved by downgrading the versions, please feel free to re-open the issue. Thanks.

**Comment by RenYang-home** [comment] 2021-01-18 19:08
Which tensorflow and tensorflow-compression versions do you use? Since we pre-trained the models on tensorflow 1.12 and tensorflow-compression 1.0 (refer to readme), the codes are currently not compatible with higher versions.

We are not planning to release the training codes. Sorry for the inconvenience.

I will currently close this comment, if the problem is not solved by downgrading the versions, please feel free to re-open the issue. Thanks.

**Closed by RenYang-home** 2021-01-18 19:08 UTC
